"""
Modify yaml generated by conda skeleton
expects the yaml class in conda/cdxbasics/meta.yaml
"""

import sys

file = sys.argv[1]
print("Reading %s" % file)
with open( file, "rt") as f:
    output = ""
    for line in f:
        line = line[:-1]
        ix = line.find("your-github-id-here")
        if ix != -1:
            output += line[:ix] + "hansbuehler\n"
            continue
        ix = line.find("script:")
        if ix != -1:            
            output += line + "\n"
            output += line[0:ix] + "noarch: python\n"
            continue
        ix = line.find("doc_url:")
        if ix != -1:
            output += line[:-1] + " https://github.com/hansbuehler/cdxbasics/blob/master/README.md\n"
            continue
        output += line + "\n"
    f.close()
    
print("Writing %s" % file)
with open( file, 'wt' ) as f:
    print(output)
    f.write(output)
    f.close()
    print("%s written" % file)
    
exit(0)
    




